services:
  nekomaid-mysql:
    container_name: nekomaid-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - nekomaid-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nekomaid-db"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  nekomaid:
    container_name: nekomaid
    image: nekomaid:latest
    depends_on:
      nekomaid-mysql:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: .docker/images/nekomaid/Dockerfile
    tty: yes
volumes:
  nekomaid-mysql:
    external: true