module.exports = {
    //Hidden
    tieup: require('./tieup'),
    shop: require('./shop'),
    d_addnetworth: require('./d_addnetworth'),
    d_addcredits: require('./d_addcredits'),
    d_addbank: require('./d_addbank'),

    d_setnetworth: require('./d_setnetworth'),
    d_setcredits: require('./d_setcredits'),
    d_setbank: require('./d_setbank'),

    update: require('./update'),
    botconfig: require('./botconfig'),
    customembed: require('./customembed'),
    eval: require('./eval'),
    d_give: require('./d_give'),
    d_giveinserver: require('./d_giveinserver'),
    rr: require('./rr'),

    //Unhidden
    help: require('./help'),
    support: require('./support'),
    invite: require('./invite'),
    info: require('./info'),
    prefix: require('./prefix'),
    upvote: require('./upvote'),
    suggest: require('./suggest'),
    ping: require('./ping'),

    arrest: require('./arrest'),
    bite: require('./bite'),
    cuddle: require('./cuddle'),
    pat: require('./pat'),
    hug: require('./hug'),
    kiss: require('./kiss'),
    kill: require('./kill'),
    poke: require('./poke'),
    tickle: require('./tickle'),
    lick: require('./lick'),
    slap: require('./slap'),
    nom: require('./nom'),
    
    angry: require('./angry'),
    blush: require('./blush'),
    borgar: require('./borgar'),
    cry: require('./cry'),
    dance: require('./dance'),
    smug: require('./smug'),
    smile: require('./smile'),
    sleepy: require('./sleepy'),
    think: require('./think'),
    lewd: require('./lewd'),
    pout: require('./pout'),
    shrug: require('./shrug'),

    coinflip: require('./coinflip'),
    roll: require('./roll'),
    "8ball": require('./8ball'),
    neko: require('./neko'),
    foxgirl: require('./foxgirl'),
    cat: require('./cat'),
    dog: require('./dog'),
    impostor: require('./impostor'),

    profile: require('./profile'),
    bal: require('./bal'),
    daily: require('./daily'),
    work: require('./work'),
    crime: require('./crime'),
    marry: require('./marry'),
    divorce: require('./divorce'),
    transfer: require('./transfer'),
    deposit: require('./deposit'),
    withdraw: require('./withdraw'),
    top: require('./top'),
    rep: require('./rep'),
    beg: require('./beg'),
    use: require('./use'),
    useall: require('./useall'),
    steal: require('./steal'),
    item: require('./item'),
    buy: require('./buy'),
    
    ass: require('./ass'),
    maid: require('./maid'),
    orgy: require('./orgy'),
    hentai: require('./hentai'),
    thighs: require('./thighs'),
    tentacles: require('./tentacles'),
    nsfwGif: require('./nsfwgif'),
    nhentai: require('./nhentai'),
    nsfwfoxgirl: require('./nsfwfoxgirl'),
    yuri: require('./yuri'),
    cum: require('./cum'),
    bj: require('./bj'),
    bdsm: require('./bdsm'),
    pussy: require('./pussy'),
    safebooru: require('./safebooru'),
    danbooru: require('./danbooru'),
    rule34: require('./rule34'),
    e621: require('./e621'),
    gelbooru: require('./gelbooru'),
    realbooru: require('./realbooru'),
    xbooru: require('./xbooru'),

    ava: require('./ava'),
    say: require('./say'),
    owoify: require('./owoify'),
    getemote: require('./getemote'),
    serverinfo: require('./serverinfo'),
    roleinfo: require('./roleinfo'),
    userinfo: require('./userinfo'),
    osu: require('./osu'),
    osuset: require('./osuset'),
    osutop: require('./osutop'),
    osulast: require('./osulast'),
    osurecent: require('./osurecent'),
    hhelp: require('./hhelp'),
    site: require('./site'),
    poll: require('./poll'),
    nicklettergiveaway: require('./nicklettergiveaway'),
    nickletterrequest: require('./nickletterrequest'),
    animetrivia: require('./animetrivia'),

    play: require('./play'),
    leave: require('./leave'),
    skip: require('./skip'),
    queue: require('./queue'),
    repeat: require('./repeat'),
    shuffle: require('./shuffle'),
    pause: require('./pause'),
    clearqueue: require('./clearqueue'),
    np: require('./np'),
    
    clear: require('./clear'),
    someone: require('./someone'),
    ban: require('./ban'),
    unban: require('./unban'),
    bans: require('./bans'),
    mute: require('./mute'),
    unmute: require('./unmute'),
    mutes: require('./mutes'),
    kick: require('./kick'),
    warn: require('./warn'),
    clearwarns: require('./clearwarns'),
    warns: require('./warns'),
    slowmode: require('./slowmode'),

    config: require('./config'),
    leveling: require('./leveling'),
    moderation: require('./moderation'),
    auditlog: require('./auditlog'),

    level: require('./level'),
    leveltop: require('./leveltop'),
    addserverxp: require('./addserverxp'),
    setserverxp: require('./setserverxp'),
    removeserverxp: require('./removeserverxp'),
    clearserverxp: require('./clearserverxp')
};
